# Generated by Django 4.2 on 2023-05-12 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Locations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.TextField(max_length=50)),
                ("state", models.TextField(max_length=50)),
                ("state_id", models.TextField(max_length=5)),
                ("longitude", models.TextField(max_length=50)),
                ("latitude", models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Zip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zipcode", models.TextField(max_length=20)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Weather.locations",
                    ),
                ),
            ],
        ),
    ]
