# Generated by Django 4.2 on 2023-05-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Weather", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="zip", old_name="article", new_name="location_id",
        ),
        migrations.AlterField(
            model_name="locations",
            name="city",
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="zip", unique_together={("zipcode", "location_id")},
        ),
    ]
