# Generated by Django 4.2 on 2023-05-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Weather",
            "0002_rename_article_zip_location_id_alter_locations_city_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="locations", name="city", field=models.TextField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="locations", unique_together={("city", "state_id")},
        ),
    ]
