# Generated by Django 4.2 on 2023-05-15 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Weather", "0003_alter_locations_city_alter_locations_unique_together"),
    ]

    operations = [
        migrations.RenameModel(old_name="Locations", new_name="Location",),
    ]
