# Generated by Django 4.2 on 2023-05-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Weather", "0004_rename_locations_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weather_icon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="weather_icon/")),
            ],
        ),
    ]
