# Generated by Django 4.2 on 2023-05-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Weather", "0005_weather_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weather_icon",
            name="image",
            field=models.FileField(upload_to="weather_icon/"),
        ),
    ]
